name: Docker Smoke Test

on:
  workflow_dispatch:
  push:
    branches: [ deploy-web-linked ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: cd web && npm ci
      - name: Build app
        run: cd web && npm run build
      - name: Docker version
        run: docker --version
      - name: Run hello-world
        run: docker run --rm hello-world
      - name: Build Docker image
        run: cd web && docker build -t lifemetrics-web:latest .